### ISSUE TITLE
Content of Images Component is not reponsive

### ISSUE THREAD

**Issue by Girishbari** [AccessibleForAll/AccessibleWebDev#264]
**Describe the bug**
There is a width problem in the image component it is not decreasing when we change the screen size 
may be setting min-width could solve the problem

**To Reproduce**
1.  Go to Live link
2.  Go to developer tools
3.  try decreasing size of screen
4.  See error

**Screenshots**
![image](https://user-images.githubusercontent.com/38005544/219865219-d11f57e4-d9ac-4099-a49b-7c5a68610e91.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by EmmaDawsonDev** [comment]
Thanks for noticing! I think this is due to an update we just made to the code block which removed some CSS

**Comment by PiseAtharva** [comment]
oh my god 🤦 can't believe I missed this completely

**Comment by EmmaDawsonDev** [comment]
Don’t worry, I missed it too. It’s easily fixed

**Comment by PiseAtharva** [comment]
can i know how ? I am literally typing out media queries for each viewport 😭 (325/400/700/...

**Comment by Girishbari** [comment]
Use vw in width

**Comment by EmmaDawsonDev** [comment]
You can look back at the css I deleted in the codeblock css file

**Comment by EmmaDawsonDev** [comment]
codeWrapper {
   background-color: var(--dark);
   color: var(--white);
   padding: 16px;
   font-size: 1rem;
   line-height: 1.6;
   white-space: pre-wrap;
   word-break: break-word;
   tab-size: 4;
 }
 
I think it’s the white space and word break that’s needed

**Comment by PiseAtharva** [comment]
Hi Emma, I believe i have found a work around for this Issue, can you also evaluate this
```javascript
<SyntaxHighlighter
	language={languageType || defaultType}
	style={dracula}
	className={styles.codeWrapper}>
	{codeSnippet}
</SyntaxHighlighter>
```
```css
.codeWrapper {
  	width: 60vw;                                     /* for 4k Screens */
	line-height: 1.6 !important;
}

.codeWrapper > code {
	white-space: pre-wrap !important;
	word-break: break-word !important;
}

@media screen and (max-width: 1440px) {
  .codeWrapper {
    width: 75vw;				      /* for Notebooks */
  }
}

@media screen and (max-width: 800px) {
  .codeWrapper {
    width: 95vw;				       /* for Tablets or smaller devices */
  }
}
```

**Comment by EmmaDawsonDev** [comment]
@PiseAtharva No need for all this. There seems to be a prop you can pass. Add wrapLongLines=true and it should fix it:
```<SyntaxHighlighter
			language={languageType}
			style={dracula}
			wrapLongLines={true}>
			{codeSnippet}
		</SyntaxHighlighter>
```

**Comment by EmmaDawsonDev** [comment]
@PiseAtharva did you want me to assign you?

**Comment by PiseAtharva** [comment]
> @PiseAtharva did you want me to assign you?

Sure

**Comment by Girishbari** [comment]
Hi @PiseAtharva, I guess this issue is still there, if you want we can collaborate

**Comment by PiseAtharva** [comment]
sure go ahead 😄
